### ISSUE TITLE
Minified React error #130

### ISSUE THREAD

**Issue by eriksachse** [justinmc/react-audio-player#135]
When I try to access the frontend in production, the site crashes and gives me the following error:

```
react_devtools_backend.js:4061 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (vendor.9baa75d4.js:34:15306)
    at Ct (vendor.9baa75d4.js:30:49488)
    at pt (vendor.9baa75d4.js:30:50970)
    at vendor.9baa75d4.js:30:53421
    at fi (vendor.9baa75d4.js:30:65214)
    at ck (vendor.9baa75d4.js:34:11576)
    at bk (vendor.9baa75d4.js:34:1025)
    at ak (vendor.9baa75d4.js:34:949)
    at Tj (vendor.9baa75d4.js:34:790)
    at Lj (vendor.9baa75d4.js:32:11738)

```

Works in local environment (Vite).
Does it has to do something with the url object?

**Comment by serg06** [comment]
The same thing started happening to me when I switched to Vite. [It's related to this issue.](https://github.com/vitejs/vite/issues/2139) react-audio-player needs to be fixed so that Rollup can use it correctly.

In the meantime here's a workaround:

```ts
// ReactAudioPlayerComponent.tsx
import ReactAudioPlayer from 'react-audio-player';
function fixComponent<T>(component: T): T {
    return (component as any).default ?? component;
}
export const ReactAudioPlayerComponent = fixComponent(ReactAudioPlayer);
```

Then when you need the types, you use `ReactAudioPlayer`, but when you need the actual component in JSX, you use `ReactAudioPlayerComponent `.

**Comment by kubukoz** [comment]
Thanks a lot @serg06, just hit this 😅
