### ISSUE TITLE
How to hide controls

### ISSUE THREAD

**Issue by ghost** [justinmc/react-audio-player#22]
How do I hide the controls?
 I am trying the following but it does not work:
`<ReactAudioPlayer  src="./assets/audio/01.mp3" controls="false" />`

All other options (loop, autoStart etc. )work as expected.

**Comment by justinmc** [comment]
Have you tried not including a controls attribute at all? Or if that doesn't work, try this: controls={false}

Warning that I'm guessing because I'm not near my laptop. Actually maybe we should change it to work with a string though. I've tried to make it work as closely to the native audio tag as I could.

**Comment by carstenheisterkamp** [comment]
Yes `controls={false} `worked, I overlooked this. Thanks!

**Comment by justinmc** [comment]
Taking another look at this.  @ghost Any opinions on how you think controls should work?  I feel inclined to match the `audio` tag api (controls defaults to false), but not sure.  I'll leave it as is unless anyone feels that we should change it.
