### ISSUE TITLE
Customize controls

### ISSUE THREAD

**Issue by tifa2UP** [justinmc/react-audio-player#23]
Hi, 

Thank you for the great project! How can customize/change the icons for the audio controls (Play, volume, etc.)? 

Thank you!

**Comment by justinmc** [comment]
Glad you're using it!  It's not possible to change the icons of the audio tag itself, which is just what this project is wrapping under the hood (i.e. [this stackoverflow question](https://stackoverflow.com/questions/3794682/custom-css-for-audio-tag#)).

However, what you can do is to set `controls` to false so that the default UI doesn't display at all, and then write up your own UI.  You can get [direct access to the audio element](https://github.com/justinmc/react-audio-player#access-to-the-audio-element) and then use the browser's audio api to play/pause/etc.

Please keep in touch if you do attempt this!  If you run into any blockers with this project's setup, I'd be happy to work with your requirements so that this sort of thing is easy.

**Comment by tifa2UP** [comment]
Thank you! I decided to go with the default settings for now.

**Comment by justinmc** [comment]
Cool, that's definitely the easiest.  Let me know if you ever try writing your own.

**Comment by ucin3d** [comment]
Is there any progress on facilitating the customization of the react-audio-player UI (icons + colors) since this issue was raised over four years ago?
