### ISSUE TITLE
onEnded {Function}

### ISSUE THREAD

**Issue by corroleaus** [justinmc/react-audio-player#5]
## onEnded {Function}

in the Api Documentation the callback function onEnded is mentioned as being called when a song completes playback. However the proper name for that callback is onEnd, usage:
```
<ReactAudioPlayer
  	src={uri}
  	autoPlay="true"
  	onEnd={this.props.onSongEnded.bind(null,id)}
/>
```

**Comment by justinmc** [comment]
Thanks for the issue!  I just took care of it in this PR https://github.com/justinmc/react-audio-player/pull/8 by renaming `onEnd` to `onEnded`.  I think that makes the most sense in order to be consistent with the browser event names ('ended') and the existing callback function names.  Be aware you'll need to change your usage to `onEnded` though if you update!
